CREATE TABLE CAR(CAR_ID serial PRIMARY KEY, CAR_NAME VARCHAR(255), CAR_MILEAGE integer);
CREATE TABLE CAR_EVENTS(EVT_ID serial PRIMARY KEY, EVT_CAR_ID integer, EVT_NAME VARCHAR(255), EVT_COST integer, EVT_NOTE VARCHAR(255));
CREATE TABLE USERS(USR_ID serial PRIMARY KEY, USR_NAME VARCHAR(255));
CREATE TABLE BALANCES(BAL_ID serial PRIMARY KEY, BAL_USR_ID integer, BAL_MONTH VARCHAR(20), BAL_YEAR integer, BAL_KMS integer, BAL_FREE_KMS integer);
CREATE TABLE TRIPS(TRP_ID serial PRIMARY KEY, TRP_DATE date, TRP_KMS integer, TRP_BALANCE bool);
CREATE TABLE TRIP_USERS(TUS_ID serial PRIMARY KEY, TUS_USR_ID integer, TUS_TRP_ID integer, TUS_KMS integer);
